version: "2"

services:
  app1:
    image: tactivos/devops-challenge:0.0.1
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "3000"
    ports:
      - "9001:3000"
  app2:
    image: tactivos/devops-challenge:0.0.2
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "3000"
    ports:
      - "8001:3000"
  db:
    image: mongo

  lb:
    image: 'haproxy:1.5'
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - app1
      - app2
    expose:
      - 80
      - 1936
    ports:
      - '80:80'
      - '70:70'


